[build-system]
requires = ["setuptools~=68.0", "wheel~=0.40.0"]
build-backend = "setuptools.build_meta"

[project]
name = "linux-voice-assistant"
version = "1.0.0"
description = "Linux voice satellite for Home Assistant"
readme = "README.md"
authors = [
    {name = "Michael Hansen", email = "mike@rhasspy.org"}
]
license = {text = "MIT"}
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "numpy>=1.23.0,<2.0.0",
    "zeroconf~=0.134.0",
    "aioesphomeapi>=28.1.2",
    "sounddevice>=0.4.6",
]

[project.urls]
"Homepage" = "https://github.com/OHF-Voice/linux-voice-assistant"

[project.optional-dependencies]
dev = [
    "pylint>=3.0.0",
    "black>=23.7.0",
]

[tool.setuptools]
packages = ["linux_voice_assistant"]
